import csv
import os
from datetime import date
from calendar import monthrange
from celery import Celery
from celery.schedules import crontab
from flask import render_template
from flask_mail import Message
from fpdf import FPDF

from .config import Config
from .extensions import db, mail
from .models import Appointment, DoctorProfile, Treatment, PatientProfile


# Initialize Celery for background jobs
celery_app = Celery("hms", broker=Config.CELERY_BROKER_URL, backend=Config.CELERY_RESULT_BACKEND)


def init_celery(app):
    """Setup Celery with Flask app context"""
    # Use explicit new-style Celery keys to avoid key-mixing errors.
    celery_app.conf.update(
        broker_url=app.config.get("CELERY_BROKER_URL"),
        result_backend=app.config.get("CELERY_RESULT_BACKEND"),
        timezone="Asia/Kolkata",
        enable_utc=False,
    )

    class FlaskTask(celery_app.Task):
        def __call__(self, *args, **kwargs):
            with app.app_context():
                return self.run(*args, **kwargs)

    celery_app.Task = FlaskTask

    # Schedule background jobs
    celery_app.conf.beat_schedule = {
        "daily-reminders": {
            "task": "app.tasks.send_daily_reminders",
            "schedule": crontab(hour=9, minute=0),  # 9 AM every day
        },
        "monthly-reports": {
            "task": "app.tasks.send_monthly_doctor_reports",
            "schedule": crontab(day_of_month=1, hour=9, minute=0),  # 1st of month, 9 AM
        },
    }


def _clip_text(value, limit):
    text = str(value or "").replace("\n", " ").strip()
    if len(text) <= limit:
        return text
    return text[: limit - 3] + "..."


def _doctor_display_name(doctor):
    raw_name = (doctor.name or doctor.user.username or "").strip()
    pretty_name = raw_name.replace("_", " ").strip()
    lowered = pretty_name.lower()
    if lowered.startswith("dr. "):
        pretty_name = pretty_name[4:].strip()
    elif lowered.startswith("dr "):
        pretty_name = pretty_name[3:].strip()
    return pretty_name.title() if pretty_name else (doctor.user.username or "")


def _add_monthly_pdf_table_header(pdf):
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(228, 237, 255)
    pdf.cell(24, 8, "Date", border=1, fill=True)
    pdf.cell(34, 8, "Patient", border=1, fill=True)
    pdf.cell(52, 8, "Diagnosis", border=1, fill=True)
    pdf.cell(50, 8, "Prescription", border=1, fill=True)
    pdf.cell(30, 8, "Notes", border=1, fill=True)
    pdf.ln(8)


def _build_monthly_pdf_report(doctor, appointments, report_month, generated_on, total_revenue):
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Header banner
    pdf.set_fill_color(11, 61, 145)
    pdf.rect(10, 10, 190, 26, "F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_xy(14, 15)
    pdf.cell(0, 7, "Hospital Management System", ln=1)
    pdf.set_x(14)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 7, f"Monthly Activity Report - {report_month}", ln=1)

    pdf.set_text_color(31, 41, 55)
    pdf.ln(5)
    pdf.set_font("Helvetica", "", 11)
    doctor_name = _doctor_display_name(doctor)
    specialization = doctor.specialization or "General"
    pdf.cell(0, 7, f"Doctor: Dr. {doctor_name} ({specialization})", ln=1)
    pdf.cell(0, 7, f"Generated On: {generated_on}", ln=1)
    pdf.cell(
        0,
        7,
        f"Completed Appointments: {len(appointments)} | Revenue: INR {total_revenue:.2f}",
        ln=1,
    )

    pdf.ln(3)
    _add_monthly_pdf_table_header(pdf)
    pdf.set_font("Helvetica", "", 9)

    if not appointments:
        pdf.cell(190, 8, "No completed appointments for this month.", border=1)
        pdf.ln(8)
    else:
        for appt in appointments:
            if pdf.get_y() > 270:
                pdf.add_page()
                _add_monthly_pdf_table_header(pdf)
                pdf.set_font("Helvetica", "", 9)

            diagnosis = appt.treatment.diagnosis if appt.treatment else "-"
            prescription = appt.treatment.prescription if appt.treatment else "-"
            notes = appt.treatment.notes if appt.treatment and appt.treatment.notes else "-"

            pdf.cell(24, 8, _clip_text(appt.date, 20), border=1)
            pdf.cell(34, 8, _clip_text(appt.patient.user.username, 24), border=1)
            pdf.cell(52, 8, _clip_text(diagnosis, 44), border=1)
            pdf.cell(50, 8, _clip_text(prescription, 42), border=1)
            pdf.cell(30, 8, _clip_text(notes, 24), border=1)
            pdf.ln(8)

    pdf.ln(5)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(100, 116, 139)
    pdf.multi_cell(0, 5, "This PDF report is auto-generated by Hospital Management System.")

    raw_pdf = pdf.output(dest="S")
    if isinstance(raw_pdf, (bytes, bytearray)):
        return bytes(raw_pdf)
    return raw_pdf.encode("latin-1")


def send_daily_reminders_sync(test_mode=False, test_recipient=None):
    """Send appointment reminders to patients scheduled for today.

    If test_mode is enabled and there are no appointments today,
    send a fallback test email to the configured mailbox.
    """
    today = date.today()
    appointments = Appointment.query.filter_by(date=today, status="Booked").all()

    sent = 0
    failed = 0
    for appt in appointments:
        try:
            patient = appt.patient.user
            doctor_profile = appt.doctor
            doctor_user = doctor_profile.user
            display_doctor_name = _doctor_display_name(doctor_profile)
            time_str = appt.time.strftime("%H:%M")
            pretty_date = today.strftime("%d %b %Y")

            html = render_template(
                "emails/daily_reminder.html",
                is_test=False,
                patient_name=patient.username,
                doctor_name=display_doctor_name,
                appointment_date=pretty_date,
                appointment_time=time_str,
                booked_count=len(appointments),
                generated_on=pretty_date,
            )

            msg = Message(
                subject=f"Appointment Reminder - {today.strftime('%B %d, %Y')}",
                recipients=[patient.email],
                body=(
                    f"Hi {patient.username},\n\n"
                    f"Reminder: Your appointment with Dr. {display_doctor_name} is today at {time_str}.\n\n"
                    "Please arrive 10 minutes early.\n\n"
                    "Thanks,\nHMS Team"
                ),
                html=html,
            )
            mail.send(msg)
            sent += 1
        except Exception as e:
            failed += 1
            print(f"Error sending reminder: {str(e)}")

    test_mail_sent = False
    if test_mode:
        try:
            recipient = test_recipient or Config.MAIL_USERNAME
            pretty_date = today.strftime("%d %b %Y")
            test_body = (
                "This is a test reminder email from HMS.\n\n"
                f"Booked appointments found for today: {len(appointments)}.\n"
                "If the count is 0, this email is a fallback test to confirm mail configuration is working."
            )

            test_html = render_template(
                "emails/daily_reminder.html",
                is_test=True,
                patient_name="Admin",
                doctor_name="Test Mail",
                appointment_date=pretty_date,
                appointment_time="N/A",
                booked_count=len(appointments),
                generated_on=pretty_date,
            )

            msg = Message(
                subject=f"Daily Reminder Test - {today.strftime('%B %d, %Y')}",
                recipients=[recipient],
                body=test_body,
                html=test_html,
            )
            mail.send(msg)
            sent += 1
            test_mail_sent = True
        except Exception as e:
            failed += 1
            print(f"Error sending daily reminder test mail: {str(e)}")

    return {
        "sent": sent,
        "failed": failed,
        "total": len(appointments),
        "test_mail_sent": test_mail_sent,
    }


def send_monthly_doctor_reports_sync(report_format="html"):
    """Send monthly activity reports to all doctors in HTML or PDF format."""
    report_format = (report_format or "html").strip().lower()
    if report_format not in {"html", "pdf"}:
        report_format = "html"

    today = date.today()
    year, month = today.year, today.month
    first_day = date(year, month, 1)
    last_day = date(year, month, monthrange(year, month)[1])
    report_month = today.strftime("%B %Y")
    generated_on = today.strftime("%d %b %Y")

    doctors = DoctorProfile.query.all()
    sent = 0
    failed = 0

    for doctor in doctors:
        try:
            completed = Appointment.query.filter(
                Appointment.doctor_id == doctor.id,
                Appointment.status == "Completed",
                Appointment.date >= first_day,
                Appointment.date <= last_day,
            ).all()

            total_revenue = sum((a.paid_amount or 0.0) for a in completed)
            html = render_template(
                "emails/monthly_report.html",
                doctor=doctor,
                doctor_display_name=_doctor_display_name(doctor),
                appointments=completed,
                report_month=report_month,
                generated_on=generated_on,
                total_revenue=f"{total_revenue:.2f}",
            )

            msg = Message(
                subject=f"Monthly Report ({report_format.upper()}) - {report_month}",
                recipients=[doctor.user.email],
            )

            if report_format == "pdf":
                pdf_data = _build_monthly_pdf_report(
                    doctor=doctor,
                    appointments=completed,
                    report_month=report_month,
                    generated_on=generated_on,
                    total_revenue=total_revenue,
                )
                safe_name = (doctor.user.username or "doctor").replace(" ", "_")
                msg.body = "Your monthly activity report is attached as a PDF document."
                msg.html = html
                msg.attach(
                    filename=f"monthly_report_{safe_name}_{year}_{month:02d}.pdf",
                    content_type="application/pdf",
                    data=pdf_data,
                )
            else:
                msg.body = f"Your monthly activity report for {report_month} is included in this email."
                msg.html = html

            mail.send(msg)
            sent += 1
        except Exception as e:
            failed += 1
            print(f"Error sending report: {str(e)}")

    return {"sent": sent, "failed": failed, "total": len(doctors), "format": report_format}


@celery_app.task(name="app.tasks.send_daily_reminders")
def send_daily_reminders():
    return send_daily_reminders_sync()


@celery_app.task(name="app.tasks.send_monthly_doctor_reports")
def send_monthly_doctor_reports():
    return send_monthly_doctor_reports_sync(report_format="html")


@celery_app.task(name="app.tasks.export_patient_treatments_csv")
def export_patient_treatments_csv(patient_id):
    """Export patient's treatment history as CSV file"""
    export_dir = os.path.join(Config.INSTANCE_DIR, "exports")
    os.makedirs(export_dir, exist_ok=True)
    
    filepath = os.path.join(export_dir, f"patient_{patient_id}_treatments.csv")
    
    # Get all appointments for patient
    appointments = Appointment.query.filter_by(patient_id=patient_id).all()
    
    # Write CSV
    with open(filepath, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["Date", "Time", "Doctor", "Status", "Diagnosis", "Prescription", "Notes"])
        
        for appt in appointments:
            treatment = appt.treatment if appt.treatment else None
            writer.writerow([
                appt.date,
                appt.time.strftime("%H:%M"),
                _doctor_display_name(appt.doctor),
                appt.status,
                treatment.diagnosis if treatment else "",
                treatment.prescription if treatment else "",
                treatment.notes if treatment else "",
            ])
    
    # Send notification email
    try:
        patient = PatientProfile.query.get(patient_id)
        if patient:
            msg = Message(
                subject="Your Treatment Export is Ready",
                recipients=[patient.user.email],
                body="Your treatment history has been exported as CSV. You can download it from your dashboard."
            )
            mail.send(msg)
    except Exception as e:
        print(f"Error sending notification: {str(e)}")
    
    return filepath
